name: "Build and Deployment of example application"

on :
  push:
    branches: abcd

jobs:
    
  build:
    uses: markov-ngz/az-containerapp-starterpack/.github/workflows/build.yaml@main
    permissions:
      id-token: write
      contents: read
    secrets: inherit
    with:
      application_working_directory: az-cosmos-example
      image_registry_name: ${{ vars.ACR_NAME}}
      image_name: example # the tag is set to the commit id 
      image_tag: ${{github.sha}}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment: production
    steps:
      - name: Azure login
        uses: azure/login@v2 # choose latest version 
        with:
            client-id: ${{ secrets.AZURE_CLIENT_ID }}
            tenant-id: ${{ secrets.AZURE_TENANT_ID }}
            subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Blue Green Deployment 
        uses: markov-ngz/containerapp-bluegreen-deploy@v1.0.3
        with:
            resource_group_name: ${{vars.RESOURCE_GROUP_NAME}}
            container_app_name: ${{vars.CONTAINER_APP_NAME}}
            image_full_name:  ${{ needs.build.outputs.image_fullname}}
            environment_variables: EXAMPLE=Raskolnikov